name: Build and deploy ASP.Net Core app to Azure Web App - eshoponweb-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      # 1️⃣ Clonar el repo
      - uses: actions/checkout@v4

      # 2️⃣ Instalar .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 3️⃣ Publicar solo el proyecto Web
      - name: Publish Web project
        working-directory: ./src/Web
        run: dotnet publish Web.csproj --configuration Release --output ../../publish

      # 4️⃣ Subir el artifact para el deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish   # carpeta que contiene los archivos publicados

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for OIDC
      contents: read # Required for actions/checkout

    steps:
      # 1️⃣ Descargar el artifact del job build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish   # debe coincidir con la carpeta usada en deploy

      # 2️⃣ Login a Azure usando OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_17F47F73A7024CD1B74244CD84F6BD36 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_732465639C68413EA8238446CB77BB05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B5A0349772841AF88D40F5E06EF66B5 }}

      # 3️⃣ Desplegar en Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eshoponweb-demo'
          slot-name: 'Production'
          package: ./publish
